/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#0c0c14',
        'surface-dim': '#09090f',
        'surface-bright': '#25223c',
        'surface-container-lowest': '#06060a',
        'surface-container-low': '#110f1d',
        'surface-container': '#161327',
        'surface-container-high': '#1f1b36',
        'surface-container-highest': '#2b2746',
        'on-surface': '#ffffff',
        'on-surface-variant': '#9e9ab8',
        'inverse-surface': '#ffffff',
        'inverse-on-surface': '#161327',
        outline: '#7c779b',
        'outline-variant': '#2b2746',
        'surface-tint': '#9d86e9',
        primary: '#9d86e9',
        'on-primary': '#0c0c14',
        'primary-container': '#262144',
        'on-primary-container': '#cbbcf6',
        'inverse-primary': '#7c5ee0',
        secondary: '#f59e0b',
        'on-secondary': '#1c1202',
        'secondary-container': '#382a14',
        'on-secondary-container': '#fcd34d',
        tertiary: '#38bdf8',
        'on-tertiary': '#0c0c14',
        'tertiary-container': '#153147',
        'on-tertiary-container': '#7dd3fc',
        error: '#f87171',
        'on-error': '#0c0c14',
        'error-container': '#451a1a',
        'on-error-container': '#fca5a5',
        'primary-fixed': '#cbbcf6',
        'primary-fixed-dim': '#9d86e9',
        'on-primary-fixed': '#0c0c14',
        'on-primary-fixed-variant': '#6741d9',
        background: '#0c0c14',
        'on-background': '#ffffff',
        'surface-variant': '#1f1b36',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.25rem',
        'space-xl': '1.5rem',
        'space-2xl': '2rem',
        'space-3xl': '3rem',
        'gutter-mobile': '1rem',
        'gutter-tablet': '1.5rem',
        'dock-inset-bottom': '1.5rem',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'code-sm': ['Inter', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.4s ease-out forwards',
        'slide-up': 'slideUp 0.5s ease-out forwards',
        'scale-in': 'scaleIn 0.3s ease-out forwards',
        'float': 'float 3s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 2s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        fadeInUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          from: { opacity: '0', transform: 'translateY(24px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.92)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        'glow-pulse': {
          '0%, 100%': { boxShadow: '0 0 12px rgba(208, 188, 255, 0.3)' },
          '50%': { boxShadow: '0 0 24px rgba(208, 188, 255, 0.6)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      boxShadow: {
        'glow-primary': '0 0 20px rgba(208, 188, 255, 0.3), 0 0 60px rgba(208, 188, 255, 0.1)',
        'glow-secondary': '0 0 16px rgba(255, 176, 205, 0.3)',
        'glass': '0 8px 32px rgba(0, 0, 0, 0.4), inset 0 1px 0 rgba(255, 255, 255, 0.04)',
        'card': '0 4px 16px rgba(0, 0, 0, 0.25)',
        'card-hover': '0 12px 40px rgba(0, 0, 0, 0.3), 0 0 0 1px rgba(208, 188, 255, 0.15)',
        'dock': '0 8px 32px rgba(0, 0, 0, 0.5)',
      },
    },
  },
  plugins: [],
};
